image: 'maven:latest'
stages:
  - test
  - package

test:
  stage: test
  script:
    - "mvn clean verify -Dsonar.host.url=http://192.168.99.100:9000"

package:
  stage: package
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - "**/target/*.war"
