before_script:
  - |
    echo oracle-java8-installer shared/accepted-oracle-license-v1-1 select true | debconf-set-selections && \
    add-apt-repository -y ppa:webupd8team/java && \
    apt-get update -qq && \
    apt-get install -y -qq oracle-java8-installer maven

stages:
  - test
  - package

test:
  stage: test
  script:
    - mvn clean test

package:
  stage: package
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - "**/target/*.war"
