image: 'maven:latest'
stages:
  - test
  - package

test:
  stage: test
  script:
    - mvn clean verify

package:
  stage: package
  script:
    - mvn package -DskipTests
  artifacts:
    paths:
      - "**/target/*.war"
