image: 'maven:latest'

cache:
  key: '$CI_BUILD_REF_NAME'
  paths:
    - '/root/.m2/'

build:
  script:
    - "mvn clean compile"
  artifacts:
    paths:
      - "**/target/*.war" 
    expire_in: "1 week"
