image: 'maven:latest'

cache:
  key: 'all'
  paths:
    - '~/.m2/'

services:
  - selenium/standalone-firefox

stages:
  - test
  - package

test:
  stage: test
  script:
    - |
      mvn clean verify \\
      -Dsonar.host.url=http://192.168.99.100:9000 \\
      -DbaseUrl=http://maven:8080/ \\
      -DhubUrl=http://selenium__standalone-firefox:4444/

package:
  stage: package
  script:
    - "mvn package -DskipTests"
  artifacts:
    paths:
      - "**/target/*.war"
