image: 'maven:3.3.9'

cache:
  key: '$CI_BUILD_REF_NAME'
  paths:
    - '/root/.m2/'


package:
  script:
    - "mvn package -DskipTests"
  artifacts:
    paths:
      - "**/target/*.war" 
    expire_in: "1 week"
